LANG_CODES_LINK = "https://cloud.google.com/translate/docs/languages"

LANGUAGES = {
    "af": {"name": "Afrikaans", "flag": "🇿🇦", "top": True},
    "sq": {"name": "Albanian", "flag": "🇦🇱", "top": False},
    "am": {"name": "Amharic", "flag": "🇪🇹", "top": False},
    "ar": {"name": "Arabic", "flag": "🇸🇦", "top": True},
    "hy": {"name": "Armenian", "flag": "🇦🇲", "top": False},
    "as": {"name": "Assamese", "flag": "", "top": False},
    "ay": {"name": "Aymara", "flag": "", "top": False},
    "az": {"name": "Azerbaijani", "flag": "🇦🇿", "top": False},
    "bm": {"name": "Bambara", "flag": "", "top": False},
    "eu": {"name": "Basque", "flag": "", "top": False},
    "be": {"name": "Belarusian", "flag": "🇧🇾", "top": False},
    "bn": {"name": "Bengali", "flag": "🇧🇩", "top": False},
    "bho": {"name": "Bhojpuri", "flag": "", "top": False},
    "bs": {"name": "Bosnian", "flag": "🇧🇦", "top": False},
    "bg": {"name": "Bulgarian", "flag": "🇧🇬", "top": False},
    "ca": {"name": "Catalan", "flag": "", "top": False},
    "ceb": {"name": "Cebuano", "flag": "", "top": False},
    "zh-cn": {"name": "Chinese (Simplified)", "flag": "🇨🇳", "top": True},
    "zh-tw": {"name": "Chinese (Traditional)", "flag": "🇨🇳", "top": True},
    "co": {"name": "Corsican", "flag": "", "top": False},
    "hr": {"name": "Croatian", "flag": "🇭🇷", "top": False},
    "cs": {"name": "Czech", "flag": "🇨🇿", "top": False},
    "da": {"name": "Danish", "flag": "🇩🇰", "top": True},
    "dv": {"name": "Dhivehi", "flag": "🇲🇻", "top": False},
    "doi": {"name": "Dogri", "flag": "", "top": False},
    "nl": {"name": "Dutch", "flag": "🇳🇱", "top": True},
    "en": {"name": "English", "flag": "🇬🇧", "top": True},
    "eo": {"name": "Esperanto", "flag": "", "top": False},
    "et": {"name": "Estonian", "flag": "🇪🇪", "top": False},
    "ee": {"name": "Ewe", "flag": "", "top": False},
    "fil": {"name": "Filipino (Tagalog)", "flag": "🇵🇭", "top": False},
    "fi": {"name": "Finnish", "flag": "🇫🇮", "top": True},
    "fr": {"name": "French", "flag": "🇫🇷", "top": True},
    "fy": {"name": "Frisian", "flag": "", "top": False},
    "gl": {"name": "Galician", "flag": "", "top": False},
    "ka": {"name": "Georgian", "flag": "🇬🇪", "top": False},
    "de": {"name": "German", "flag": "🇩🇪", "top": True},
    "el": {"name": "Greek", "flag": "🇬🇷", "top": False},
    "gn": {"name": "Guarani", "flag": "", "top": False},
    "gu": {"name": "Gujarati", "flag": "", "top": False},
    "ht": {"name": "Haitian Creole", "flag": "🇭🇹", "top": False},
    "ha": {"name": "Hausa", "flag": "", "top": False},
    "haw": {"name": "Hawaiian", "flag": "", "top": False},
    "he": {"name": "Hebrew", "flag": "🇮🇱", "top": True},
    "hi": {"name": "Hindi", "flag": "🇮🇳", "top": True},
    "hmn": {"name": "Hmong", "flag": "", "top": False},
    "hu": {"name": "Hungarian", "flag": "🇭🇺", "top": True},
    "is": {"name": "Icelandic", "flag": "🇮🇸", "top": False},
    "ig": {"name": "Igbo", "flag": "", "top": False},
    "ilo": {"name": "Ilocano", "flag": "", "top": False},
    "id": {"name": "Indonesian", "flag": "🇮🇩", "top": True},
    "ga": {"name": "Irish", "flag": "🇮🇪", "top": False},
    "it": {"name": "Italian", "flag": "🇮🇹", "top": True},
    "ja": {"name": "Japanese", "flag": "🇯🇵", "top": True},
    "jv": {"name": "Javanese", "flag": "", "top": False},
    "kn": {"name": "Kannada", "flag": "", "top": False},
    "kk": {"name": "Kazakh", "flag": "🇰🇿", "top": False},
    "km": {"name": "Khmer", "flag": "", "top": False},
    "rw": {"name": "Kinyarwanda", "flag": "", "top": False},
    "gom": {"name": "Konkani", "flag": "", "top": False},
    "ko": {"name": "Korean", "flag": "🇰🇷", "top": True},
    "kri": {"name": "Krio", "flag": "", "top": False},
    "ku": {"name": "Kurdish", "flag": "🇮🇶", "top": False},
    "ckb": {"name": "Kurdish (Sorani)", "flag": "🇮🇶", "top": False},
    "ky": {"name": "Kyrgyz", "flag": "🇰🇬", "top": False},
    "lo": {"name": "Lao", "flag": "🇱🇦", "top": False},
    "la": {"name": "Latin", "flag": "", "top": True},
    "lv": {"name": "Latvian", "flag": "🇱🇻", "top": False},
    "ln": {"name": "Lingala", "flag": "", "top": False},
    "lt": {"name": "Lithuanian", "flag": "🇱🇹", "top": False},
    "lg": {"name": "Luganda", "flag": "", "top": False},
    "lb": {"name": "Luxembourgish", "flag": "🇱🇺", "top": False},
    "mk": {"name": "Macedonian", "flag": "🇲🇰", "top": False},
    "mai": {"name": "Maithili", "flag": "", "top": False},
    "mg": {"name": "Malagasy", "flag": "", "top": False},
    "ms": {"name": "Malay", "flag": "🇲🇾", "top": False},
    "ml": {"name": "Malayalam", "flag": "", "top": False},
    "mt": {"name": "Maltese", "flag": "🇲🇹", "top": False},
    "mi": {"name": "Maori", "flag": "", "top": False},
    "mr": {"name": "Marathi", "flag": "", "top": False},
    "mni-Mtei": {"name": "Meiteilon (Manipuri)", "flag": "", "top": False},
    "lus": {"name": "Mizo", "flag": "", "top": False},
    "mn": {"name": "Mongolian", "flag": "🇲🇳", "top": False},
    "my": {"name": "Myanmar (Burmese)", "flag": "🇲🇲", "top": False},
    "ne": {"name": "Nepali", "flag": "🇳🇵", "top": False},
    "no": {"name": "Norwegian", "flag": "🇳🇴", "top": False},
    "ny": {"name": "Nyanja (Chichewa)", "flag": "🇲🇼", "top": False},
    "or": {"name": "Odia (Oriya)", "flag": "", "top": False},
    "om": {"name": "Oromo", "flag": "🇪🇹", "top": False},
    "ps": {"name": "Pashto", "flag": "🇦🇫", "top": False},
    "fa": {"name": "Persian", "flag": "🇮🇷", "top": False},
    "pl": {"name": "Polish", "flag": "🇵🇱", "top": True},
    "pt": {"name": "Portuguese", "flag": "🇵🇹", "top": True},
    "pa": {"name": "Punjabi", "flag": "🇵🇰", "top": False},
    "qu": {"name": "Quechua", "flag": "", "top": False},
    "ro": {"name": "Romanian", "flag": "🇷🇴", "top": True},
    "ru": {"name": "Russian", "flag": "🇷🇺", "top": True},
    "sm": {"name": "Samoan", "flag": "🇼🇸", "top": False},
    "sa": {"name": "Sanskrit", "flag": "", "top": False},
    "gd": {"name": "Scots Gaelic", "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "top": False},
    "nso": {"name": "Sepedi", "flag": "", "top": False},
    "sr": {"name": "Serbian", "flag": "🇷🇸", "top": False},
    "st": {"name": "Sesotho", "flag": "🇱🇸", "top": False},
    "sn": {"name": "Shona", "flag": "", "top": False},
    "sd": {"name": "Sindhi", "flag": "", "top": False},
    "si": {"name": "Sinhala (Sinhalese)", "flag": "🇱🇰", "top": False},
    "sk": {"name": "Slovak", "flag": "🇸🇰", "top": False},
    "sl": {"name": "Slovenian", "flag": "🇸🇮", "top": False},
    "so": {"name": "Somali", "flag": "🇸🇴", "top": False},
    "es": {"name": "Spanish", "flag": "🇪🇸", "top": True},
    "su": {"name": "Sundanese", "flag": "", "top": False},
    "sw": {"name": "Swahili", "flag": "🇹🇿", "top": False},
    "sv": {"name": "Swedish", "flag": "🇸🇪", "top": True},
    "tl": {"name": "Tagalog (Filipino)", "flag": "🇵🇭", "top": False},
    "tg": {"name": "Tajik", "flag": "🇹🇯", "top": False},
    "ta": {"name": "Tamil", "flag": "", "top": False},
    "tt": {"name": "Tatar", "flag": "", "top": False},
    "te": {"name": "Telugu", "flag": "", "top": False},
    "th": {"name": "Thai", "flag": "🇹🇭", "top": False},
    "ti": {"name": "Tigrinya", "flag": "🇪🇷", "top": False},
    "ts": {"name": "Tsonga", "flag": "", "top": False},
    "tr": {"name": "Turkish", "flag": "🇹🇷", "top": False},
    "tk": {"name": "Turkmen", "flag": "🇹🇲", "top": False},
    "ak": {"name": "Twi (Akan)", "flag": "", "top": False},
    "uk": {"name": "Ukrainian", "flag": "🇺🇦", "top": False},
    "ur": {"name": "Urdu", "flag": "🇵🇰", "top": False},
    "ug": {"name": "Uyghur", "flag": "", "top": False},
    "uz": {"name": "Uzbek", "flag": "🇺🇿", "top": False},
    "vi": {"name": "Vietnamese", "flag": "🇻🇳", "top": True},
    "cy": {"name": "Welsh", "flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "top": False},
    "xh": {"name": "Xhosa", "flag": "", "top": False},
    "yi": {"name": "Yiddish", "flag": "", "top": False},
    "yo": {"name": "Yoruba", "flag": "", "top": False},
    "zu": {"name": "Zulu", "flag": "", "top": False},
}

LANGUAGES_BY_NAME = {
    "Afrikaans": "af",
    "Albanian": "sq",
    "Amharic": "am",
    "Arabic": "ar",
    "Armenian": "hy",
    "Assamese": "as",
    "Aymara": "ay",
    "Azerbaijani": "az",
    "Bambara": "bm",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bhojpuri": "bho",
    "Bosnian": "bs",
    "Bulgarian": "bg",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Chinese (Simplified)": "zh-cn",
    "Chinese (Traditional)": "zh-tw",
    "Corsican": "co",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dhivehi": "dv",
    "Dogri": "doi",
    "Dutch": "nl",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Ewe": "ee",
    "Filipino (Tagalog)": "fil",
    "Finnish": "fi",
    "French": "fr",
    "Frisian": "fy",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Guarani": "gn",
    "Gujarati": "gu",
    "Haitian Creole": "ht",
    "Hausa": "ha",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hmong": "hmn",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Ilocano": "ilo",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kinyarwanda": "rw",
    "Konkani": "gom",
    "Korean": "ko",
    "Krio": "kri",
    "Kurdish": "ku",
    "Kurdish (Sorani)": "ckb",
    "Kyrgyz": "ky",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Luganda": "lg",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Maithili": "mai",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Maori": "mi",
    "Marathi": "mr",
    "Meiteilon (Manipuri)": "mni-Mtei",
    "Mizo": "lus",
    "Mongolian": "mn",
    "Myanmar (Burmese)": "my",
    "Nepali": "ne",
    "Norwegian": "no",
    "Nyanja (Chichewa)": "ny",
    "Odia (Oriya)": "or",
    "Oromo": "om",
    "Pashto": "ps",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Quechua": "qu",
    "Romanian": "ro",
    "Russian": "ru",
    "Samoan": "sm",
    "Sanskrit": "sa",
    "Scots Gaelic": "gd",
    "Sepedi": "nso",
    "Serbian": "sr",
    "Sesotho": "st",
    "Shona": "sn",
    "Sindhi": "sd",
    "Sinhala (Sinhalese)": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Spanish": "es",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tagalog (Filipino)": "tl",
    "Tajik": "tg",
    "Tamil": "ta",
    "Tatar": "tt",
    "Telugu": "te",
    "Thai": "th",
    "Tigrinya": "ti",
    "Tsonga": "ts",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Twi (Akan)": "ak",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uyghur": "ug",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Welsh": "cy",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Yoruba": "yo",
    "Zulu": "zu",
}
